- name: Create keycloak_postgres volume
  docker_volume:
    name: "{{ keycloak_db_volume }}"

- name: Create keycloak database
  include_role:
    name: docker-systemd-service
  vars:
    container_name: keycloak_postgres
    container_image: postgres
    container_env:
      POSTGRES_DB: "{{ keycloak_db_name }}"
      POSTGRES_USER: "{{ keycloak_db_user }}"
      POSTGRES_PASSWORD: "{{ keycloak_db_password }}"
    container_volumes:
      - "{{ keycloak_db_volume }}:/var/lib/postgresql/data"
      
- name: Create keycloak service
  include_role:
    name: docker-systemd-service
  vars:
    container_name: keycloak
    container_image: jboss/keycloak
    container_labels:
      - "traefik.backend=auth"
      - "traefik.frontend.rule=Host:auth.{{ app_domain }}"
    container_links:
      - keycloak_postgres
    container_env:
      KEYCLOAK_USER: "{{ keycloak_admin_user }}"
      KEYCLOAK_PASSWORD: "{{ keycloak_admin_password }}"
      DB_VENDOR: postgres
      DB_ADDR: keycloak_postgres
      DB_DATABASE: "{{ keycloak_db_name }}"
      DB_USER: "{{ keycloak_db_user }}"
      DB_PASSWORD: "{{ keycloak_db_password }}"
      PROXY_ADDRESS_FORWARDING: "true"