- name: Traefik
  import_playbook: playbooks/traefik.yml

- name: Admin
  import_playbook: playbooks/admin.yml

- name: Website
  import_playbook: playbooks/website.yml

# - name: Keycloak
#   import_playbook: playbooks/auth.yml

