- name: Traefik
  import_playbook: playbooks/traefik.yml

- name: Admin
  import_playbook: playbooks/admin.yml

- name: atc
  hosts: traefik
  roles:
    - atc

# - name: Keycloak
#   import_playbook: playbooks/auth.yml

