- name: Create volume for jupyter-notebooks
  docker_volume:
    name: "jupyter_notebooks_{{ id | default('jupyter') }}"

- name: Create jupyter-notebook systemd service
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    name: "jupyter_{{ id | default('jupyter') }}"
    container_image: jupyter/scipy-notebook
    container_volumes:
      - "jupyter_notebooks_{{ id | default('jupyter') }}:/home/jovyan/work"
    container_labels:
      - "traefik.frontend.rule=Host:{{ id | default('jupyter') }}.{{ app_domain }}"
