- name: Create traefik config directory
  file: path="{{ homelab_conf }}/traefik" state=directory

- name: Create traefik config file
  template:
    src: traefik.toml.j2
    dest: "{{ homelab_conf }}/traefik/traefik.toml"
    mode: 0600

- name: Create traefik environment file
  template:
    src: environment.j2
    dest: "{{ homelab_conf }}/traefik/environment"
    mode: 0600

- name: Create acme volume
  docker_volume:
    name: "traefik_acme"

- name: Create traefik systemd container service
  include_role:
    name: docker-systemd-service
  vars:
    container_name: traefik
    container_image: traefik:latest
    container_ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    container_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ homelab_conf }}/traefik:/etc/traefik"
      - "traefik_acme:/etc/traefik/acme"
    container_labels:
      - "traefik.backend=proxy"
      - "traefik.frontend.rule=Host:{{ inventory_hostname }}"
    container_args: >-
      --env-file {{ homelab_conf }}/traefik/environment
